type=real
test_tokenApiURL=https://t-apis.hanafnapimarket.com:22001/onegw/hbk/api/oauth/oauth/token
test_searchApiURL=https://t-apis.hanafnapimarket.com:22001/onegw/hbk/api/hbk-service/v1/nonFace/acctInfo
test_clientId=a1f4352c-a1f8-4bd8-bbc3-87310913eba3
test_clientSecret=46af178b8ed742290adbfc76aa93f18a08d2128
test_encKey=mtouch0001R200529002
test_entrCd=MTO0470055
test_appKey=3572d7b60d4e45b4976c07d299942f9c
test_cryptokey=yGXMeC5TP3xHkmX5+Yk03PZ1wYZ3JbdEYnRNcmDTd64vL9V1aW4hdzSeJ86ztLSo
real_tokenApiURL=https://apis.hanafnapimarket.com:22001/onegw/hbk/api/oauth/oauth/token
real_searchApiURL=https://apis.hanafnapimarket.com:22001/onegw/hbk/api/hbk-service/v1/nonFace/acctInfo
real_clientId=4dcf3866-7959-4d07-a322-36aeb6912201
real_clientSecret=25faedfee97e754b5678d220ebb66000
real_encKey=mtouch0001R200527002
real_entrCd=MTO0470055
real_appKey=ced035a5895b4f0e863c02607d105fa6
real_cryptokey=6wCPEeQ0egkz3mPaE3R3MMGGW3KNoxunQBTcnow5g80VU431JHHPtYKLM0VDAgkU
startDate=
endDate=